// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.0;

// DO NOT EDIT — AUTO-GENERATED BY packages/data/buildings/buildings.mjs

import {BuildingType, BuildingLevelInfo} from "./Buildings.sol";

abstract contract BuildingsData {
    // Maps (building type, level) to building level info.
    mapping(BuildingType => mapping(uint32 => BuildingLevelInfo)) internal levelInfo;

    constructor() {
        // Mineral Mine

        levelInfo[BuildingType.MINERAL_MINE][0] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
        levelInfo[BuildingType.MINERAL_MINE][1] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
        levelInfo[BuildingType.MINERAL_MINE][2] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
        levelInfo[BuildingType.MINERAL_MINE][3] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
        levelInfo[BuildingType.MINERAL_MINE][4] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });

        // Gas Extractor

        levelInfo[BuildingType.GAS_EXTRACTOR][0] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
        levelInfo[BuildingType.GAS_EXTRACTOR][1] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
        levelInfo[BuildingType.GAS_EXTRACTOR][2] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
        levelInfo[BuildingType.GAS_EXTRACTOR][3] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
        levelInfo[BuildingType.GAS_EXTRACTOR][4] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });

        // Deuterium Synthesizer

        levelInfo[BuildingType.DEUTERIUM_SYNTHESIZER][0] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
        levelInfo[BuildingType.DEUTERIUM_SYNTHESIZER][1] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
        levelInfo[BuildingType.DEUTERIUM_SYNTHESIZER][2] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
        levelInfo[BuildingType.DEUTERIUM_SYNTHESIZER][3] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
        levelInfo[BuildingType.DEUTERIUM_SYNTHESIZER][4] = BuildingLevelInfo({
            costMineral: 0,
            costGas: 0,
            costDeuterium: 0,
            productionRate: 0,
            constructionTime: 0
        });
    }
}
